# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .post_user import PostUser
from .user_answers import UserAnswers
from .. import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: PostUser=None, answers: UserAnswers=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param user: The user of this Body.  # noqa: E501
        :type user: PostUser
        :param answers: The answers of this Body.  # noqa: E501
        :type answers: UserAnswers
        """
        self.swagger_types = {
            'user': PostUser,
            'answers': UserAnswers
        }

        self.attribute_map = {
            'user': 'user',
            'answers': 'answers'
        }

        self._user = user
        self._answers = answers

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> PostUser:
        """Gets the user of this Body.


        :return: The user of this Body.
        :rtype: PostUser
        """
        return self._user

    @user.setter
    def user(self, user: PostUser):
        """Sets the user of this Body.


        :param user: The user of this Body.
        :type user: PostUser
        """

        self._user = user

    @property
    def answers(self) -> UserAnswers:
        """Gets the answers of this Body.


        :return: The answers of this Body.
        :rtype: UserAnswers
        """
        return self._answers

    @answers.setter
    def answers(self, answers: UserAnswers):
        """Sets the answers of this Body.


        :param answers: The answers of this Body.
        :type answers: UserAnswers
        """

        self._answers = answers
