# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class GetUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, nick: str=None):  # noqa: E501
        """GetUser - a model defined in Swagger

        :param id: The id of this GetUser.  # noqa: E501
        :type id: int
        :param nick: The nick of this GetUser.  # noqa: E501
        :type nick: str
        """
        self.swagger_types = {
            'id': int,
            'nick': str
        }

        self.attribute_map = {
            'id': 'id',
            'nick': 'nick'
        }

        self._id = id
        self._nick = nick

    @classmethod
    def from_dict(cls, dikt) -> 'GetUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetUser of this GetUser.  # noqa: E501
        :rtype: GetUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this GetUser.


        :return: The id of this GetUser.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this GetUser.


        :param id: The id of this GetUser.
        :type id: int
        """

        self._id = id

    @property
    def nick(self) -> str:
        """Gets the nick of this GetUser.


        :return: The nick of this GetUser.
        :rtype: str
        """
        return self._nick

    @nick.setter
    def nick(self, nick: str):
        """Sets the nick of this GetUser.


        :param nick: The nick of this GetUser.
        :type nick: str
        """

        self._nick = nick
