# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class UserAnswersInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, question_id: UserAnswersInnerQuestionId=None):  # noqa: E501
        """UserAnswersInner - a model defined in Swagger

        :param question_id: The question_id of this UserAnswersInner.  # noqa: E501
        :type question_id: UserAnswersInnerQuestionId
        """
        self.swagger_types = {
            'question_id': UserAnswersInnerQuestionId
        }

        self.attribute_map = {
            'question_id': 'question_id'
        }

        self._question_id = question_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserAnswersInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserAnswers_inner of this UserAnswersInner.  # noqa: E501
        :rtype: UserAnswersInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question_id(self) -> UserAnswersInnerQuestionId:
        """Gets the question_id of this UserAnswersInner.


        :return: The question_id of this UserAnswersInner.
        :rtype: UserAnswersInnerQuestionId
        """
        return self._question_id

    @question_id.setter
    def question_id(self, question_id: UserAnswersInnerQuestionId):
        """Sets the question_id of this UserAnswersInner.


        :param question_id: The question_id of this UserAnswersInner.
        :type question_id: UserAnswersInnerQuestionId
        """

        self._question_id = question_id
