---
swagger: "2.0"
info:
  description: "This is a documentation for Quizmous API"
  version: "0.0.1"
  title: "Quizmous API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "MIT"
    url: "https://github.com/szykol/quizmous-api/blob/master/LICENSE"
host: "localhost"
tags:
- name: "quiz"
  description: "Cool Anonymous Quizes"
  externalDocs:
    description: "GitHub"
    url: "https://github.com/szykol/quizmous-api"
schemes:
- "http"
paths:
  /quiz:
    get:
      tags:
      - "quiz"
      summary: "Return all existing Quizes"
      description: ""
      operationId: "get_quiz"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Question"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
    post:
      tags:
      - "quiz"
      summary: "Add a new quiz to backend"
      description: ""
      operationId: "add_quiz"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Quiz object that gets added to backend"
        required: true
        schema:
          $ref: "#/definitions/Quiz"
      responses:
        "405":
          description: "Invalid input"
        "409":
          description: "Quiz already exists"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
    put:
      tags:
      - "quiz"
      summary: "Update an existing Quiz"
      description: ""
      operationId: "update_quiz"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Quiz object that gets added to backend"
        required: true
        schema:
          $ref: "#/definitions/Quiz"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
        "405":
          description: "Validation exception"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
  /quiz/{id}:
    get:
      tags:
      - "quiz"
      summary: "Find Quiz by ID"
      description: "Returns a single quiz"
      operationId: "get_quiz_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of quiz to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Quiz"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
    delete:
      tags:
      - "quiz"
      summary: "Deletes a Quiz"
      description: ""
      operationId: "delete_quiz"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Quiz id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Successful deletion"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
  /quiz/{id}/answers:
    post:
      tags:
      - "quiz"
      summary: "Insert questions for quiz"
      description: "Returns a single quiz"
      operationId: "insert_answers_for_quiz"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of quiz to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Quiz"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
  /user/register:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Register new user."
      operationId: "create_user"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/PostUser"
      responses:
        "201":
          description: "Successful register"
          schema:
            $ref: "#/definitions/GetUser"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/login:
    post:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "login_user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Registered user"
        required: true
        schema:
          $ref: "#/definitions/PostUser"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid username/password supplied"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/logout:
    post:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logout_user"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Registered user"
        required: true
        schema:
          $ref: "#/definitions/PostUser"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid username/password supplied"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "delete_user"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Registered user"
        required: true
        schema:
          $ref: "#/definitions/PostUser"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid username/password supplied"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/quiz_taken/{id}:
    post:
      tags:
      - "quiz"
      summary: "Let backend know user has taken the quiz"
      description: ""
      operationId: "insert_quiz_taken"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of quiz to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/PostUser"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Quiz"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
  /user/{user_nick}/quiz_taken/{id}:
    get:
      tags:
      - "quiz"
      summary: "Find Quiz by ID"
      description: "Returns a single quiz"
      operationId: "get_quiz_taken"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of quiz to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "user_nick"
        in: "path"
        description: "ID of user"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Quiz not found"
      x-swagger-router-controller: "swagger_server.controllers.quiz_controller"
definitions:
  Quiz:
    type: "object"
    properties:
      quiz_id:
        type: "integer"
        format: "int64"
      author:
        $ref: "#/definitions/GetUser"
      name:
        type: "string"
        example: "Best Quiz Ever"
      description:
        type: "string"
        example: "This is a description of best quiz ever"
      questions:
        type: "array"
        items:
          $ref: "#/definitions/Question"
    example:
      quiz_id: 0
      author:
        nick: "nick"
        user_id: 6
      name: "Best Quiz Ever"
      questions:
      - question: "question"
        answers:
        - answer: "answer"
          answer_id: 6
        - answer: "answer"
          answer_id: 6
        type: {}
        question_id: 0
        required: true
      - question: "question"
        answers:
        - answer: "answer"
          answer_id: 6
        - answer: "answer"
          answer_id: 6
        type: {}
        question_id: 0
        required: true
      description: "This is a description of best quiz ever"
  Question:
    type: "object"
    properties:
      question_id:
        type: "integer"
        format: "int64"
      question:
        type: "string"
      type:
        $ref: "#/definitions/QuestionType"
      required:
        type: "boolean"
      answers:
        type: "array"
        items:
          $ref: "#/definitions/Answer"
    example:
      question: "question"
      answers:
      - answer: "answer"
        answer_id: 6
      - answer: "answer"
        answer_id: 6
      type: {}
      question_id: 0
      required: true
  QuestionType:
    type: "string"
    enum:
    - "YES_NO"
    - "RADIO"
    - "CHOICE"
    - "OPEN"
  Answer:
    type: "object"
    properties:
      answer_id:
        type: "integer"
        format: "int64"
      answer:
        type: "string"
    example:
      answer: "answer"
      answer_id: 6
  UserAnswers:
    $ref: "#/definitions/UserAnswers_inner"
  GetUser:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      nick:
        type: "string"
    example:
      nick: "nick"
      user_id: 6
  PostUser:
    type: "object"
    properties:
      nick:
        type: "string"
      password:
        type: "string"
        description: "This has to be hashed"
    example:
      nick: "nick"
      password: "password"
  inline_response_200:
    type: "object"
    properties:
      taken:
        type: "boolean"
    example:
      taken: true
  UserAnswers_inner_question_id:
    type: "object"
    properties:
      answer_id:
        type: "array"
        items:
          type: "integer"
      value:
        type: "string"
  UserAnswers_inner:
    type: "object"
    properties:
      question_id:
        $ref: "#/definitions/UserAnswers_inner_question_id"
  body:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/PostUser"
      answers:
        $ref: "#/definitions/UserAnswers"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
